### ISSUE TITLE
resnet.pt

### ISSUE THREAD

**Issue by masapasa** [al-jshen/pytorch-flask-react#1]
Traceback (most recent call last):
  File "deploy.py", line 91, in <module>
    model = init_model()
  File "deploy.py", line 82, in init_model
    resnet.load_state_dict(torch.load('resnet.pt', map_location='cpu'))
  File "C:\ProgramData\Anaconda3\envs\PythonCPU\lib\site-packages\torch\serialization.py", line 382, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'resnet.pt'

**Comment by al-jshen** [comment]
Previously didn't upload the model because of the large file size. Added in the the latest commit.
